apiVersion: v1
kind: Service
metadata:
  name: ac-service
  namespace: dark-tower
  labels:
    app: ac-service
    component: auth
spec:
  type: ClusterIP
  selector:
    app: ac-service
    component: auth
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8082
  - name: http
    protocol: TCP
    port: 8082
    targetPort: 8082
  sessionAffinity: None
